# Muhammad Hassan Farid
# FA24-RAI-012

## **Quiz-2**

Perform following tasks on the provided Reviews Dataset.
* Drop words if not alphabets.
* Tokenize the sentence.
* Perform lemitization.
* Vectorize using bigram and trigram techniques.
* Apply Random Forest algorithm with 150 trees.
* Evaluate overall accuracy of the model and class-wise precision .

In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np


In [93]:
df  = pd.read_csv('/content/reviews_dataset.csv')
df.head()

news      type
0  China had role in Yukos split-up\n \n China le...  business
1  Oil rebounds from weather effect\n \n Oil pric...  business
2  Indonesia 'declines debt freeze'\n \n Indonesi...  business
3  $1m payoff for former Shell boss\n \n Shell is...  business
4  US bank in $515m SEC settlement\n \n Five Bank...  business

In [94]:
df.shape

(2225, 2)

In [95]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2225 entries, 0 to 2224
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   news    2225 non-null   object
 1   type    2225 non-null   object
dtypes: object(2)
memory usage: 34.9+ KB


In [96]:
df.describe()

news   type
count                                                2225   2225
unique                                               2127      5
top     What high-definition will do to DVDs\n \n Firs...  sport
freq                                                    2    511

In [97]:
df['type'].value_counts()

type
sport            511
business         510
politics         417
tech             401
entertainment    386
Name: count, dtype: int64

In [98]:
df.duplicated().sum()

98

In [99]:
df.isnull().sum()

news    0
type    0
dtype: int64

In [100]:
# Removing Duplicates
df.drop_duplicates(inplace=True)

In [101]:
df.shape

(2127, 2)

In [102]:
# Lower Casing
df['news'] = df['news'].str.lower()

In [103]:
# Removing HTML tags
import re
def remove_html_tags(text):
    pattern = re.compile('<.*?>')
    return pattern.sub(r'', text)

df['news'] = df['news'].apply(remove_html_tags)

In [104]:
# Remove Url
def remove_url(text):
    pattern = re.compile(r'https?://\S+|www\.\S+')
    return pattern.sub(r'', text)
df['news'] = df['news'].apply(remove_url)

In [105]:
exclude = "!.,?"
def remove_punc(text):
    return text.translate(str.maketrans('', '', exclude))

df['news'] = df['news'].apply(remove_punc)


In [106]:
df.head()

news      type
0  china had role in yukos split-up\n \n china le...  business
1  oil rebounds from weather effect\n \n oil pric...  business
2  indonesia 'declines debt freeze'\n \n indonesi...  business
3  $1m payoff for former shell boss\n \n shell is...  business
4  us bank in $515m sec settlement\n \n five bank...  business

In [107]:
df['news'] = df['news'].str.replace('\n', '', regex=True)

In [108]:
df['news'][1]

'oil rebounds from weather effect  oil prices recovered in asian trade on tuesday after falling in new york on milder winter weather across the us  with winter temperatures staying relatively high in the northern us a barrel of light crude ended monday down $133 to $4212 however crude prices have rebounded in asia rising to $4230 a barrel for february delivery in london trading of brent crude was suspended for a public holiday but the price fell to $3920 in the far east  with milder temperatures expected to continue in the northern parts of the us over the next few days at least analysts have said the price of oil may fall further - even if the decline was only temporary "weather has been the achilles\' heel of this market" said abn amro analyst john brady "but it is winter in the northeast eventually we\'ll get another cold blast" despite a fall of more than $12 a barrel from the record highs reached in late october the price of crude oil remains almost 30% higher than year-ago levels

In [89]:
df.sample(10)

news           type
514   spark heads world booker list    dame muriel s...  entertainment
912   defiant hunts put ban to the test    thousands...       politics
1427  classy henman makes winning start    tim henma...          sport
2038  gadget show heralds mp3 christmas    partners ...           tech
970   blunkett tells of love and pain    david blunk...       politics
1009  kilroy launches 'veritas' party    ex-bbc chat...       politics
181   europe blames us over weak dollar    european ...       business
536   buffy creator joins wonder woman    the creato...  entertainment
1335  iaaf launches fight against drugs    the iaaf ...          sport
692   hollywood ready for oscars night    hollywood ...  entertainment

'oil rebounds from weather effect    oil prices recovered in asian trade on tuesday after falling in new york on milder winter weather across the us    with winter temperatures staying relatively high in the northern us a barrel of light crude ended monday down $133 to $4212 however crude prices have rebounded in asia rising to $4230 a barrel for february delivery in london trading of brent crude was suspended for a public holiday but the price fell to $3920 in the far east    with milder temperatures expected to continue in the northern parts of the us over the next few days at least analysts have said the price of oil may fall further - even if the decline was only temporary "weather has been the achilles\' heel of this market" said abn amro analyst john brady "but it is winter in the northeast eventually we\'ll get another cold blast" despite a fall of more than $12 a barrel from the record highs reached in late october the price of crude oil remains almost 30% higher than year-ago 

In [16]:
# Removing Stopwords
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [17]:
from nltk.corpus import stopwords
def remove_stopwords(text):
    new_text = []

    for word in text.split():
        if word in stopwords.words('english'):
            new_text.append('')
        else:
            new_text.append(word)
    x = new_text[:]
    new_text.clear()
    return " ".join(x)

df['news'] = df['news'].apply(remove_stopwords)

In [18]:
import nltk
nltk.download('wordnet')
from nltk.stem import WordNetLemmatizer
lemmitizer = WordNetLemmatizer()

[nltk_data] Downloading package wordnet to /root/nltk_data...


In [19]:
# Tokenization
def lemmatize_words(tokens):
    return [lemmitizer.lemmatize(word,pos='v') for word in tokens]

df['news'] = df['news'].apply(lemmatize_words)

In [43]:
from sklearn.preprocessing import LabelEncoder

X = df['news']
Y = df['type']

encoder = LabelEncoder()
Y = encoder.fit_transform(Y)
Y

array([0, 0, 0, ..., 4, 4, 4])

In [44]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(X,Y,test_size=0.2,random_state=42)

print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(1701,)
(426,)
(1701,)
(426,)


In [110]:
# Bigram
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score,confusion_matrix
cv = CountVectorizer(ngram_range=(2,2))

X_train_n_gram = cv.fit_transform(X_train)
X_test_n_gram = cv.transform(X_test)

print(f"Shape of X_train_bow: {X_train_n_gram.shape}")
print(f"Shape of X_test_bow: {X_test_n_gram.shape}")

rf1 = RandomForestClassifier(max_depth=5,n_estimators=150,random_state=25)

rf1.fit(X_train_n_gram,y_train)
y_pred = rf1.predict(X_test_n_gram)

print (accuracy_score(y_test,y_pred))
print (confusion_matrix(y_test,y_pred))

Shape of X_train_bow: (1701, 281683)
Shape of X_test_bow: (426, 281683)
0.5845070422535211
[[92  0  1 11  0]
 [31  7  0 40  0]
 [12  0 42 19  0]
 [ 1  0  0 97  0]
 [39  0  0 23 11]]


In [113]:
# Triple Gra
cv = CountVectorizer(ngram_range=(3,3))

X_train_n_gram = cv.fit_transform(X_train)
X_test_n_gram = cv.transform(X_test)

print(f"Shape of X_train_bow: {X_train_n_gram.shape}")
print(f"Shape of X_test_bow: {X_test_n_gram.shape}")

rf2 = RandomForestClassifier(max_depth=200,n_estimators=200,random_state=25)

rf2.fit(X_train_n_gram,y_train)
y_pred = rf2.predict(X_test_n_gram)

print (accuracy_score(y_test,y_pred))
print (confusion_matrix(y_test,y_pred))

Shape of X_train_bow: (1701, 507183)
Shape of X_test_bow: (426, 507183)
0.7793427230046949
[[91  1  3  8  1]
 [15 49  1 12  1]
 [ 7  0 57  9  0]
 [ 0  0  0 98  0]
 [21  4  2  9 37]]
